import { z } from "zod";

const numeric = z.coerce.number().min(0);

export const onboardingSchema = z.object({
  name: z.string().min(2),
  dateOfBirth: z.string().min(8),
  age: numeric,
  occupation: z.string().min(2),
  city: z.string().min(2),
  maritalStatus: z.string().min(1),
  monthlySalary: numeric,
  bonusIncome: numeric,
  sideIncome: numeric,
  otherIncome: numeric,
  monthlyCashInflow: numeric,
  rent: numeric,
  emi: numeric,
  loans: numeric,
  subscriptions: numeric,
  creditCardDebt: numeric,
  monthlyExpenses: numeric,
  stocksValue: numeric,
  mutualFundsValue: numeric,
  cryptoValue: numeric,
  goldValue: numeric,
  epfPpfValue: numeric,
  realEstateValue: numeric,
  cashBalance: numeric,
  additionalInvestments: z.array(z.object({ type: z.string(), value: numeric, notes: z.string().optional() })),
  shortTermLossTolerance: z.string().min(1),
  shortTermHorizon: z.string().min(1),
  shortTermVolatilityComfort: z.string().min(1),
  opportunityPreference: z.string().min(1),
  drawdownTolerance: z.string().min(1),
  volatilityComfort: z.string().min(1),
  liquidityRequirement: z.string().min(1),
  investmentHorizon: z.string().min(1),
  retirementAge: z.coerce.number().min(40).max(80),
  emergencyFundTarget: numeric,
  housePurchaseTarget: numeric,
  travelTarget: numeric,
  internationalTrips: numeric,
  domesticTrips: numeric,
  internationalTripCost: numeric,
  domesticTripCost: numeric,
  retirementTarget: numeric,
  retirementInputType: z.string().min(1),
  retirementMonthlyIncome: numeric,
  retirementYearlyIncome: numeric,
  expectedInflation: numeric,
  lifeExpectancy: z.coerce.number().min(60).max(110),
  postRetirementReturn: numeric,
  financialFreedomTarget: numeric,
  financialFreedomInputType: z.string().min(1),
  passiveMonthlyIncome: numeric,
  passiveYearlyIncome: numeric,
  withdrawalRate: numeric,
  housePlan: z.object({
    mode: z.enum(["lumpsum", "emi"]),
    interestRate: numeric,
    tenureYears: z.coerce.number().min(1).max(30),
    downPayment: numeric
  }),
  spendingDiscipline: z.string().min(1),
  emotionalSpendingTendency: z.string().min(1),
  investmentPsychology: z.string().min(1),
  riskReaction: z.string().min(1),
  tracksExpenses: z.string().min(1),
  investsMonthly: z.string().min(1),
  panicSellRisk: z.string().min(1)
});
